### ISSUE TITLE
Port boolean* functions and tests

### ISSUE THREAD

**Issue by armantorkzaban** [dartclub/turf_dart#88]
- [x]  booleanClockwise
- [x]  booleanConcave
- [x]  booleanContains
- [x]  booleanCrosses
- [x]  booleanDisjoint
- [x]  booleanEqual
- [x]  booleanIntersects
- [x]  booleanParallel
- [x]  booleanPointInPolygon
- [x]  booleanPointOnLine
- [x] booleanTouches
- [x] #131

**implement peer dependencies:**

- [x] WIP geojson-equality https://github.com/geosquare/geojson-equality -> https://github.com/dartclub/turf_equality
- [x] https://github.com/rowanwins/point-in-polygon-hao -> https://github.com/dartclub/point_in_polygon
  > While point-in-polygon is slightly faster in most cases it does not support polygons with holes or degenerate polygons.
- [x] https://github.com/dartclub/turf_dart/issues/95
- [x] https://github.com/dartclub/turf_dart/issues/97
- [x] [blocking] rhumb_bearing & its test #107 –> #109
- [x] PolygonToLine - part of #101 
- [x] LineToPolygon - part of #101
- [x] cleanCoords #112
- [x] truncate #114
- [x] https://github.com/dartclub/turf_dart/issues/94

**Comment by lukas-h** [comment]
Inspiration:
https://github.com/mfogel/polygon-clipping

**Comment by armantorkzaban** [comment]
@lukas-h, 
what do you think about implementing 'properties' for FeatureCollection class? 
During working with unit tests I saw a few occasions where it was used in the geojson files for featureCollections, and I think it could be in some cases beneficial.

**Comment by lukas-h** [comment]
@armantorkzaban Are you referring to a `properties` member for FeatureCollection? I would try to avoid that, since that is not part of the GeoJSON-RFC.

**Comment by lukas-h** [comment]
Yes, let's avoid it for now, but in the future, #44 will be implemented.

**Comment by lukas-h** [comment]
GitHub projects, I started one, but didn't have the time to complete it. We will have a backlog and sprints in separate boards there.

**Comment by lukas-h** [comment]
https://github.com/orgs/dartclub/projects/1

**Comment by armantorkzaban** [comment]
After the discovery another blocking dependencies (rbush) we decided to separated the dependant libraries from this PR and work on them separately. Therefore the task list is shortened and PR will be marked as ready for review.

**Comment by armantorkzaban** [comment]
the issue definition is updated.
